version: '3.9'
services:
  web:
    build: .
    container_name: vertikal_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db/vertikal_agent
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: vertikal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vertikal_agent
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: vertikal_adminer
    restart: always
    ports:
      - "8080:8080"